# Generated by Django 4.2.1 on 2023-05-23 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="book",
            name="Cover",
            field=models.CharField(
                choices=[("Hard", "Hard"), ("Soft", "Soft")], max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
