# Generated by Django 4.2.1 on 2023-05-24 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_options_alter_book_cover_and_more"),
        (
            "borrowings",
            "0002_remove_borrowing_book_id_remove_borrowing_user_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="books.book"
            ),
        ),
    ]
